[package]
name = "mag"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.8"
gtk = "0.18.2"
image = "0.25.5"
log = "0.4.27"
screenshots = "0.8.10"
sdl2 = { version = "0.37.0", features = ["image"] }
tray-icon = "0.20.0"
